<Project>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <LangVersion>latest</LangVersion>
    <Version>0.1.0</Version>
    <Product>HBK Wwise</Product>
    <Authors>akmubi</Authors>
    <Company>akmubi</Company>
    <Copyright>Copyright © 2026 akmubi</Copyright>
    <Description>Wwise audio modding workbench for Hi-Fi RUSH.</Description>
    <NeutralLanguage>en</NeutralLanguage>
  </PropertyGroup>
</Project>
